/**
 * ID: record
 * Description: Sales record table
 */
CREATE TABLE F4211 ( 
/*Record ID*/ REID INTEGER , 
/*Product ID*/ REIMID INTEGER , 
/*Employee ID*/ REEMID SMALLINT , 
/*Quantity*/ REQTY SMALLINT , 
/*Created Time*/ RECREATED DATE );
ALTER TABLE F4211 ADD CONSTRAINT F4211_PRIMARY PRIMARY KEY ( REID );
ALTER TABLE F4211 ADD CONSTRAINT F4211_REFERENCE_1 FOREIGN KEY ( REIMID ) REFERENCES F4101 ( IMID );
ALTER TABLE F4211 ADD CONSTRAINT F4211_REFERENCE_2 FOREIGN KEY ( REEMID ) REFERENCES F0101 ( EMID );
CREATE SEQUENCE F4211_REID MINVALUE 0 START WITH 1;